language: objective-c #语言种类

xcode_project: Framework/LEEAlert/LEEAlert.xcodeproj # 项目文件相对于.travis.yml文件的路径
    
xcode_scheme: LEEAlert #你需要集成测试的scheme

osx_image: xcode11

script:
- xcodebuild clean build -sdk iphonesimulator -project Framework/LEEAlert/LEEAlert.xcodeproj -scheme LEEAlert CODE_SIGNING_REQUIRED=NO
